### ISSUE TITLE
scripts/tartan: fails to parse clang version in debian

### ISSUE THREAD

**Issue by justinjoy** [pwithnall/tartan#2]
Normally, clang --version returns like:

```
 clang version 3.3 (tags/RELEASE_33/rc3)
```

However, it has different strings in some packages.
In case of debian jessie, the returns is like:

```
 Debian clang version 3.5.0-10 (tags/RELEASE_350/final) (based on LLVM 3.5.0)
```

Therefore, scripts/tartan fails to parse clang_version_full from this string.

**Comment by pwithnall** [comment]
This was fixed in commit 1cc535bcb81ae407d5a10269208384c967e27c85. Thanks for filing the issue (sorry it took so long for me to actually catch up with it and close it).
